import sys
import os
import pytest

# Adds the parent directory (root) to the system path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from tools import list_tables, get_schema, search_business_rule, execute_query


### Test list_tables

def test_list_tables_success():
    result = list_tables.invoke({})
    assert isinstance(result, list)
    assert len(result) > 0
    assert "Customers" in result


### Test get_schema

def test_get_schema_success():
    # Testing with a known valid table
    result = get_schema.invoke({"table_name": "Customers"})
    assert isinstance(result, str)
    assert "CREATE TABLE" in result

def test_get_schema_invalid_table():
    # Testing the error handling logic we added
    result = get_schema.invoke({"table_name": "NonExistentTable"})
    assert isinstance(result, dict)
    assert "error" in result
    assert "not found" in result["error"]


### Test search_business_rule

## Test 1: Successful query with rules returned

@pytest.mark.parametrize("query, expected", [
    ("gross margin", "* **Gross Margin:** Assumed to be 30% of Revenue."),
    ("COGS", "* **Cost of Goods Sold (COGS):** Assumed to be 70% of Revenue."),
    ("revenue", "* **Revenue:** Calculated as sum of `Products.price` * `Order_Items.quantity`."),
    ("profit", "* **Profit:** Calculated as Revenue - COGS."),
    ("AOV", "* **Average Order Value (AOV):** Total Revenue divided by total number of orders."),
    ("VIPs", "* **VIP customer:** A customer whose order totals exceeds $1000."),
    ("repeat customers", "* **Repeat customer:** A customer who made two or more orders."),
    ("churn", "* **Churned customer:** A customer whose most recent order is more than 30 days ago."),
    ("CLV", "* **Customer Lifetime Value (CLV):** Total Revenue generated by a specific customer across all their orders."),
    ("active products", "* **Active Product:** A product with at least 1 unit sold within the last 30 days."),
    ("underperforming products", "* **Underperforming Product:** A product with less than 3 units sold in the last 60 days.")
])
def test_search_business_rule_valid(query, expected):
    result = search_business_rule.invoke({"query": query})
    assert expected in result

## Test 2: No relevant rules found

def test_search_business_rule_no_results():
    result = search_business_rule.invoke({"query": "non_existent_rule_xyz"})
    assert "message" in result
    assert "No relevant business rules" in result["message"]


### Test execute_query

## Test 1: Successful query with data returned

def test_execute_query_returns_data():
    query = "SELECT product_id, name, price, category FROM Products LIMIT 1;"
    result = execute_query.invoke({"query": query})
    assert isinstance(result, str)
    assert "error" not in result
    assert "returned no results" not in result


## Test 2: No relevant data found

def test_execute_query_returns_no_data():
    query = "SELECT customer_id FROM Orders WHERE order_id = -999;"
    result = execute_query.invoke({"query": query})
    assert "message" in result
    assert "returned no results" in result["message"]


## Test 3: Forbidden commands

@pytest.mark.parametrize("forbidden_query", [
    "DROP TABLE Orders;",
    "TRUNCATE TABLE Logs;",
    "DELETE FROM Products;"
    "UPDATE Customers SET name = 'Hacked';",
    "INSERT INTO Products (name) VALUES ('Ghost');",
    "ALTER TABLE Users ADD COLUMN password TEXT;",
])
def test_execute_query_forbidden_commands(forbidden_query):
    result = execute_query.invoke({"query": forbidden_query})
    assert isinstance(result, dict)
    assert "error" in result
    assert "Forbidden keyword detected" in result["error"]


## Test 4: Incorrect table or column name

def test_execute_query_incorrect_table():
    query = "SELECT customer_id FROM NonExistentTable"
    result = execute_query.invoke({"query": query})
    assert "error" in result
    assert "no such table" in result["error"]

def test_execute_query_incorrect_column():
    query = "SELECT NonExistentColumn FROM Customers"
    result = execute_query.invoke({"query": query})
    assert "error" in result
    assert "no such column" in result["error"]